### ISSUE TITLE
Exercises with several names

### ISSUE THREAD

**Issue by quanvo87** [colbywhite/weight-program-schema#1]
What happens in the case of someone trying to look up `Seated Bent-Over Rear Delt Raise`, will `Seated Delt Raise`return the same result, and `Delt Raise`? Perhaps each exercise has some sort of `root` name, then many potential modifiers?

Are dumbbell curls different than barbell curls?

**Comment by colbywhite** [comment]
```
        {
          "name": "Dumbbell Curls",
          "sets": 5,
          "reps": 5
        },
        {
          "name": "Barbell Curls",
          "sets": 5,
          "reps": 5
        }
```

If the name is different, then they should be different, right? the name is effectively the id in the current scheme. (That might not be great for the long term, but it suffices for now I think.)

**Comment by quanvo87** [comment]
OK, agreed. Those are actually different. As far as the first issue, doesn't seem that relevant now that I understand the purpose of this project a bit more.
